package com.fabins.entity;

import com.fabins.entity.enums.ContactInquiryStatus;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.Instant;
import java.util.UUID;

/**
 * A general visitor inquiry submitted through the FABINS homepage
 * "Let's Connect" contact form.
 *
 * <p>This entity is separate from {@link DeploymentRequest}, which carries
 * deep RMG technical specifications for factory retrofit assessments. A contact
 * inquiry is intentionally simpler: a person sends a message, and the R&amp;D
 * team replies.
 *
 * <p>This is the <em>persistence model</em> and is never returned directly
 * from a controller. Responses are shaped by {@code ContactInquiryResponse}
 * instead, which keeps internal fields (future: assigned team member, reply
 * notes) from leaking into the public API.
 *
 * <h2>Why UUID primary keys</h2>
 * The id is handed to the submitter in the API response as part of a reference
 * code. Sequential integer ids would allow anyone to enumerate how many
 * inquiries the business has received. UUIDs are opaque and non-guessable.
 */
@Entity
@Table(name = "contact_inquiry")
@EntityListeners(AuditingEntityListener.class)
public class ContactInquiry {

    /**
     * Surrogate UUID key, generated by the application rather than the database
     * (via JPA's {@code @GeneratedValue} default, which uses a UUID strategy
     * when the field is of type {@link UUID}).
     */
    @Id
    @GeneratedValue
    private UUID id;

    /**
     * Full name of the person enquiring.
     * Mirrors the {@code @Size(max = 200)} on {@code CreateContactInquiry}.
     */
    @Column(nullable = false, length = 200)
    private String name;

    /**
     * Email address for reply. Validated to be a well-formed address by
     * {@code @Email} in the request DTO before reaching this entity.
     * 320 characters = RFC 5321 maximum.
     */
    @Column(nullable = false, length = 320)
    private String email;

    /**
     * Subject line of the inquiry (e.g. "Partnership Inquiry", "Technical Question").
     * Mirrors the {@code @Size(max = 300)} on {@code CreateContactInquiry}.
     */
    @Column(nullable = false, length = 300)
    private String subject;

    /**
     * Free-text message body.
     * Mirrors the {@code @Size(max = 4000)} on {@code CreateContactInquiry}.
     */
    @Column(nullable = false, length = 4000)
    private String message;

    /**
     * Current workflow stage. Stored as the enum constant's {@link #name()}
     * string so that re-ordering the enum never corrupts persisted rows.
     *
     * <p>All new inquiries start as {@link ContactInquiryStatus#NEW}.</p>
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private ContactInquiryStatus status;

    /**
     * UTC instant when the inquiry was first persisted, written once by
     * {@link AuditingEntityListener} and never updated.
     */
    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /**
     * UTC instant of the most recent update, kept current by
     * {@link AuditingEntityListener} on every {@code merge}.
     */
    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    // ──────────────────────────────────────────────────────────────────────────
    // Factory
    // ──────────────────────────────────────────────────────────────────────────

    /**
     * Creates a new {@code ContactInquiry} ready for persistence with status
     * {@link ContactInquiryStatus#NEW}. Timestamps are set by JPA auditing on
     * the first {@code persist} call.
     *
     * @param name    submitter's full name
     * @param email   submitter's email address
     * @param subject subject line of the inquiry
     * @param message free-text message body
     * @return a transient entity (not yet persisted)
     */
    public static ContactInquiry create(String name, String email,
                                        String subject, String message) {
        ContactInquiry inquiry = new ContactInquiry();
        inquiry.name    = name;
        inquiry.email   = email;
        inquiry.subject = subject;
        inquiry.message = message;
        inquiry.status  = ContactInquiryStatus.NEW;
        return inquiry;
    }

    /**
     * Builds a short, human-readable tracking reference from the first 8
     * characters of the UUID.
     *
     * <p>Format: {@code FAB-CONTACT-XXXXXXXX} (uppercase hex). Used in the
     * API response and in the sender-confirmation email so the enquirer can
     * quote it when following up.
     *
     * @return e.g. {@code FAB-CONTACT-A1B2C3D4}
     */
    public String getReferenceCode() {
        return "FAB-CONTACT-" + id.toString().replace("-", "").substring(0, 8).toUpperCase();
    }

    /**
     * Transitions the inquiry status to {@link ContactInquiryStatus#REPLIED}.
     *
     * <p>Called by {@code ContactInquiryServiceImpl#acknowledge(UUID)} when the
     * R&amp;D team clicks the one-click acknowledge link in the admin notification
     * email. The transition is intentionally idempotent: calling this method on
     * an inquiry that is already {@code REPLIED} simply keeps the same status.
     */
    public void markReplied() {
        this.status = ContactInquiryStatus.REPLIED;
    }

    // ──────────────────────────────────────────────────────────────────────────
    // Getters — no setters; use the factory method and status transitions only
    // ──────────────────────────────────────────────────────────────────────────

    /** @return the surrogate UUID primary key */
    public UUID getId() { return id; }

    /** @return the submitter's full name */
    public String getName() { return name; }

    /** @return the submitter's email address */
    public String getEmail() { return email; }

    /** @return the subject line of the inquiry */
    public String getSubject() { return subject; }

    /** @return the free-text message body */
    public String getMessage() { return message; }

    /** @return the current workflow status */
    public ContactInquiryStatus getStatus() { return status; }

    /** @return the UTC instant the inquiry was first persisted */
    public Instant getCreatedAt() { return createdAt; }

    /** @return the UTC instant the inquiry was last updated */
    public Instant getUpdatedAt() { return updatedAt; }
}
