package com.fabins.entity;

import com.fabins.entity.enums.DeploymentRequestStatus;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.Instant;
import java.util.UUID;

/**
 * A mill's request to have FABINS assessed for their inspection frames.
 *
 * <p>This is the persistence model and is deliberately never returned from a
 * controller. Responses use {@code DeploymentRequestResponse} instead, so that
 * adding an internal column here — sales notes, an assigned engineer — cannot
 * accidentally leak into the public API.
 *
 * <h2>Why the column lengths are what they are</h2>
 * They mirror the {@code @Size} limits on {@code CreateDeploymentRequest} and
 * the {@code varchar} widths in {@code V1__create_deployment_request.sql}. All
 * three must agree: validation rejects oversized input before it reaches the
 * database, and the database is the last line of defence if it ever does.
 */
@Entity
@Table(name = "deployment_request")
@EntityListeners(AuditingEntityListener.class)
public class DeploymentRequest {

    /**
     * Surrogate key, generated by the application rather than the database.
     *
     * <p>A UUID is used instead of a sequence so that request identifiers are
     * not guessable — the id appears in the {@code Location} header returned to
     * an anonymous submitter, and sequential ids would let anyone enumerate how
     * many enquiries the business has received.
     */
    @Id
    @GeneratedValue
    private UUID id;

    @Column(name = "mill_name", nullable = false, length = 200)
    private String millName;

    @Column(name = "contact_name", nullable = false, length = 200)
    private String contactName;

    @Column(nullable = false, length = 320)
    private String email;

    /** Optional — the form does not require a phone number. */
    @Column(length = 50)
    private String phone;

    /** Optional free text describing fabric types, roll widths, and volume. */
    @Column(length = 5000)
    private String message;

    /** Optional designation / job title of contact representative. */
    @Column(length = 150)
    private String designation;

    /** Factory location / city / country. */
    @Column(length = 200)
    private String location;

    /** Type of RMG / Textile factory. */
    @Column(name = "factory_type", length = 100)
    private String factoryType;

    /** Number of inspection frames to retrofit/upgrade. */
    @Column(name = "inspection_frames_count", length = 50)
    private String inspectionFramesCount;

    /** Types of fabric processed. */
    @Column(name = "fabric_types", length = 500)
    private String fabricTypes;

    /** Daily/monthly production volume. */
    @Column(name = "daily_production_volume", length = 100)
    private String dailyProductionVolume;

    /** Target inspection speed. */
    @Column(name = "inspection_speed", length = 50)
    private String inspectionSpeed;

    /** Roll width or table width. */
    @Column(name = "roll_width", length = 50)
    private String rollWidth;

    /** Primary defect types of concern. */
    @Column(name = "defect_types", length = 500)
    private String defectTypes;

    /** Target ERP system for software integration. */
    @Column(name = "erp_integration_needed", length = 100)
    private String erpIntegrationNeeded;

    /** Implementation timeline. */
    @Column(name = "target_timeline", length = 100)
    private String targetTimeline;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private DeploymentRequestStatus status;

    /** Set once, by JPA auditing, when the row is first inserted. */
    @CreatedDate
    @Column(name = "submitted_at", nullable = false, updatable = false)
    private Instant submittedAt;

    /** Refreshed by JPA auditing on every update. */
    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** Required by JPA. Not for application use — call {@link #submit}. */
    protected DeploymentRequest() {
    }

    private DeploymentRequest(String millName, String contactName, String designation, String email,
                              String phone, String location, String factoryType,
                              String inspectionFramesCount, String fabricTypes,
                              String dailyProductionVolume, String inspectionSpeed,
                              String rollWidth, String defectTypes, String erpIntegrationNeeded,
                              String targetTimeline, String message) {
        this.millName = millName;
        this.contactName = contactName;
        this.designation = designation;
        this.email = email;
        this.phone = phone;
        this.location = location;
        this.factoryType = factoryType;
        this.inspectionFramesCount = inspectionFramesCount;
        this.fabricTypes = fabricTypes;
        this.dailyProductionVolume = dailyProductionVolume;
        this.inspectionSpeed = inspectionSpeed;
        this.rollWidth = rollWidth;
        this.defectTypes = defectTypes;
        this.erpIntegrationNeeded = erpIntegrationNeeded;
        this.targetTimeline = targetTimeline;
        this.message = message;
        this.status = DeploymentRequestStatus.NEW;
    }

    /**
     * Creates a newly submitted request.
     */
    public static DeploymentRequest submit(String millName, String contactName, String designation,
                                           String email, String phone, String location,
                                           String factoryType, String inspectionFramesCount,
                                           String fabricTypes, String dailyProductionVolume,
                                           String inspectionSpeed, String rollWidth,
                                           String defectTypes, String erpIntegrationNeeded,
                                           String targetTimeline, String message) {
        return new DeploymentRequest(millName, contactName, designation, email, phone, location,
                factoryType, inspectionFramesCount, fabricTypes, dailyProductionVolume,
                inspectionSpeed, rollWidth, defectTypes, erpIntegrationNeeded, targetTimeline, message);
    }

    /**
     * Backward-compatible overload for legacy callers or minimal payloads.
     */
    public static DeploymentRequest submit(String millName, String contactName, String email,
                                           String phone, String message) {
        return new DeploymentRequest(millName, contactName, null, email, phone, null,
                null, null, null, null, null, null, null, null, null, message);
    }

    /**
     * Moves this request to a new stage of the follow-up process.
     */
    public void changeStatus(DeploymentRequestStatus newStatus) {
        this.status = newStatus;
    }

    public UUID getId() {
        return id;
    }

    public String getMillName() {
        return millName;
    }

    public String getContactName() {
        return contactName;
    }

    public String getDesignation() {
        return designation;
    }

    public String getEmail() {
        return email;
    }

    public String getPhone() {
        return phone;
    }

    public String getLocation() {
        return location;
    }

    public String getFactoryType() {
        return factoryType;
    }

    public String getInspectionFramesCount() {
        return inspectionFramesCount;
    }

    public String getFabricTypes() {
        return fabricTypes;
    }

    public String getDailyProductionVolume() {
        return dailyProductionVolume;
    }

    public String getInspectionSpeed() {
        return inspectionSpeed;
    }

    public String getRollWidth() {
        return rollWidth;
    }

    public String getDefectTypes() {
        return defectTypes;
    }

    public String getErpIntegrationNeeded() {
        return erpIntegrationNeeded;
    }

    public String getTargetTimeline() {
        return targetTimeline;
    }

    public String getMessage() {
        return message;
    }

    public DeploymentRequestStatus getStatus() {
        return status;
    }

    public Instant getSubmittedAt() {
        return submittedAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Contextual human-readable reference code for email notifications and customer support.
     * Format: FAB-2026-[SHORT_UUID], e.g. FAB-2026-ABB5B9D6
     */
    public String getReferenceCode() {
        if (id == null) {
            return "FAB-2026-PENDING";
        }
        return "FAB-2026-" + id.toString().split("-")[0].toUpperCase();
    }
}
