package com.fabins.entity;

import com.fabins.entity.enums.DeploymentRequestStatus;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.Instant;
import java.util.UUID;

/**
 * A mill's request to have FABINS assessed for their inspection frames.
 *
 * <p>This is the persistence model and is deliberately never returned from a
 * controller. Responses use {@code DeploymentRequestResponse} instead, so that
 * adding an internal column here — sales notes, an assigned engineer — cannot
 * accidentally leak into the public API.
 *
 * <h2>Why the column lengths are what they are</h2>
 * They mirror the {@code @Size} limits on {@code CreateDeploymentRequest} and
 * the {@code varchar} widths in {@code V1__create_deployment_request.sql}. All
 * three must agree: validation rejects oversized input before it reaches the
 * database, and the database is the last line of defence if it ever does.
 */
@Entity
@Table(name = "deployment_request")
@EntityListeners(AuditingEntityListener.class)
public class DeploymentRequest {

    /**
     * Surrogate key, generated by the application rather than the database.
     *
     * <p>A UUID is used instead of a sequence so that request identifiers are
     * not guessable — the id appears in the {@code Location} header returned to
     * an anonymous submitter, and sequential ids would let anyone enumerate how
     * many enquiries the business has received.
     */
    @Id
    @GeneratedValue
    private UUID id;

    @Column(name = "mill_name", nullable = false, length = 200)
    private String millName;

    @Column(name = "contact_name", nullable = false, length = 200)
    private String contactName;

    @Column(nullable = false, length = 320)
    private String email;

    /** Optional — the form does not require a phone number. */
    @Column(length = 50)
    private String phone;

    /** Optional free text describing fabric types, roll widths, and volume. */
    @Column(length = 5000)
    private String message;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private DeploymentRequestStatus status;

    /** Set once, by JPA auditing, when the row is first inserted. */
    @CreatedDate
    @Column(name = "submitted_at", nullable = false, updatable = false)
    private Instant submittedAt;

    /** Refreshed by JPA auditing on every update. */
    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** Required by JPA. Not for application use — call {@link #submit}. */
    protected DeploymentRequest() {
    }

    private DeploymentRequest(String millName, String contactName, String email,
                              String phone, String message) {
        this.millName = millName;
        this.contactName = contactName;
        this.email = email;
        this.phone = phone;
        this.message = message;
        this.status = DeploymentRequestStatus.NEW;
    }

    /**
     * Creates a newly submitted request.
     *
     * <p>The only way to build one, which guarantees every request starts at
     * {@link DeploymentRequestStatus#NEW} — a caller cannot construct one that
     * is already {@code CLOSED}.
     */
    public static DeploymentRequest submit(String millName, String contactName, String email,
                                           String phone, String message) {
        return new DeploymentRequest(millName, contactName, email, phone, message);
    }

    /**
     * Moves this request to a new stage of the follow-up process.
     *
     * <p>Status is changed through this method rather than a plain setter so
     * that any future rule — forbidding a transition out of {@code CLOSED},
     * say, or recording who made the change — has one place to live.
     */
    public void changeStatus(DeploymentRequestStatus newStatus) {
        this.status = newStatus;
    }

    public UUID getId() {
        return id;
    }

    public String getMillName() {
        return millName;
    }

    public String getContactName() {
        return contactName;
    }

    public String getEmail() {
        return email;
    }

    public String getPhone() {
        return phone;
    }

    public String getMessage() {
        return message;
    }

    public DeploymentRequestStatus getStatus() {
        return status;
    }

    public Instant getSubmittedAt() {
        return submittedAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Contextual human-readable reference code for email notifications and customer support.
     * Format: FAB-2026-[SHORT_UUID], e.g. FAB-2026-ABB5B9D6
     */
    public String getReferenceCode() {
        if (id == null) {
            return "FAB-2026-PENDING";
        }
        return "FAB-2026-" + id.toString().split("-")[0].toUpperCase();
    }
}
